### ISSUE TITLE
`implicit_type` should be added to `_props`

### ISSUE THREAD

**Issue by dnorthcote** [Xilinx/ZCU111-PYNQ#22]
Package concerning: xrfdc.

The RF-DC c-drivers do not always have implicit setters and getters for one property. It is possible for a setter to be implicit while a getter is explicit and vice versa.

Consider:
`u32 XRFdc_SetFabWrVldWords(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id,
u32 FabricWrVldWords);`
and
`u32 XRFdc_GetFabWrVldWords(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32
Block_Id, u32 *FabricWrVldWordsPtr);`

The write valid words function is only for RF-DAC blocks, while the get valid words function is common for both RF-DC blocks.

When parsing the _props tuples in `__init__()` the `implicit_type` should be used for each property.

**Comment by schelleg** [comment]
We are archiving this repository.

The latest ZCU111 board files have moved to [https://github.com/Xilinx/RFSoC-PYNQ](https://github.com/Xilinx/RFSoC-PYNQ).

SD card images for the ZCU111 can be found at [http://www.pynq.io/board](http://www.pynq.io/board).

Please raise this or new issues on the <a href="https://discuss.pynq.io" target="_blank">PYNQ support forum</a>.
