### ISSUE TITLE
Improve c_type unpacking by using recursive unpacking for a c_type that contains a c_type.

### ISSUE THREAD

**Issue by dnorthcote** [Xilinx/ZCU111-PYNQ#23]
Package concerning: xrfdc.

When getting the `IPStatus` property of the rfdc class, the property returns a c_type. The xrfdc class fails to correctly unpack a c_type inside a c_type. Some sort of recursive unpacking is required to resolve this issue and simplify user interaction with the class.

**Comment by schelleg** [comment]
We are archiving this repository.

The latest ZCU111 board files have moved to [https://github.com/Xilinx/RFSoC-PYNQ](https://github.com/Xilinx/RFSoC-PYNQ).

SD card images for the ZCU111 can be found at [http://www.pynq.io/board](http://www.pynq.io/board).

Please raise this or new issues on the <a href="https://discuss.pynq.io" target="_blank">PYNQ support forum</a>.
