### ISSUE TITLE
Error with `ThresholdClearMode`

### ISSUE THREAD

**Issue by cramsay** [Xilinx/ZCU111-PYNQ#24]
The ADC tile's `ThresholdClearMode` is broken in two ways:

  1) It's calling a C function that doesn't exist ( `ThresholdClearMode` vs `ThresholdClrMode`)
  2) This is write-only C driver, so assigning a value causes an error

I think we can take this as a chance to improve the way we handle thresholding in general. Backwards compatibility isn't so important when the feature never worked! I'd suggest we add a new level in the hierarchy where each ADC block has two thresholds --- each can be independently configured and cleared.

This deviates from the C API for `XRFdc_SetThresholdSettings` a little. They have different side-effects depending on the setting's `UpdateThreshold` field... this is very unnatural for a Python property (we'd expect it to appear side-effect free), and we could easily make this a little more idiomatic.

**Comment by schelleg** [comment]
We are archiving this repository.

The latest ZCU111 board files have moved to [https://github.com/Xilinx/RFSoC-PYNQ](https://github.com/Xilinx/RFSoC-PYNQ).

SD card images for the ZCU111 can be found at [http://www.pynq.io/board](http://www.pynq.io/board).

Please raise this or new issues on the <a href="https://discuss.pynq.io" target="_blank">PYNQ support forum</a>.
