### ISSUE TITLE
Vivado IP Integrator and HDL Wrapper

### ISSUE THREAD

**Issue by jbiams77** [Xilinx/ZCU111-PYNQ#25]
I've been successfully running the provided RFSoC bitstreams with the "getting started RFSoC" project. I'm at a point now where I would like to create my own bitsream but am having trouble understanding how these overlay's map to a Vivado IP project. Is there any resources that show an IP Overlay creation in Vivado (specific to ZCU111), generate Bitstream, and create Python drivers for my custom IP Block design?  At aminimum, an example Vivado project for the ZCU111 with corresponding Overlay would be extremely helpful.

**Comment by schelleg** [comment]
We are archiving this repository.

The latest ZCU111 board files have moved to [https://github.com/Xilinx/RFSoC-PYNQ](https://github.com/Xilinx/RFSoC-PYNQ).

SD card images for the ZCU111 can be found at [http://www.pynq.io/board](http://www.pynq.io/board).

Please raise this or new issues on the <a href="https://discuss.pynq.io" target="_blank">PYNQ support forum</a>.
