### ISSUE TITLE
Dict .update() call is not propagated to C driver in xrfdc

### ISSUE THREAD

**Issue by cramsay** [Xilinx/ZCU111-PYNQ#9]
Issue raised in [this](https://discuss.pynq.io/t/rfsoc-dac-with-pynq/268/6) forum post.

When working with dict properties in the xrfdc driver, we need to catch calls to `.update()` and ensure we pass this to the C driver.

For example, this code should update a subset of the mixer settings but currently does nothing:
```python
event = xrfdc.EVNT_SRC_TILE
new_mixcfg = {
    'Freq' : 474.48,
    'PhaseOffset' : 0.1,
    'EventSource' : event
}
ol.dac_block.MixerSettings.update(new_mixcfg)
ol.dac_block.UpdateEvent(event)
```

**Comment by schelleg** [comment]
We are archiving this repository.

The latest ZCU111 board files have moved to [https://github.com/Xilinx/RFSoC-PYNQ](https://github.com/Xilinx/RFSoC-PYNQ).

SD card images for the ZCU111 can be found at [http://www.pynq.io/board](http://www.pynq.io/board).

Please raise this or new issues on the <a href="https://discuss.pynq.io" target="_blank">PYNQ support forum</a>.
